### PR TITLE
CLI stability fixes + display mono version after OS flash

### LINKED ISSUE #190: Update Meadow status message to include mono version after flashing
Currently: Updated Meadow to OS: 0.6.7.18 (Sep 13 2022 14:58:44) ESP: 0.6.7.18

Should probably match `meadow device info`

Firmware Versions - OS: 0.6.7.18 (Sep 13 2022 14:58:44) Mono: 0.6.7.18, Coprocessor: 0.6.7.18

And "Firmware Versions" doesn't sound quite right either .... maybe just "Meadow Versions" or "Meadow OS versions"

### PR DESCRIPTION
**Pull request by adrianstevens**
fixes #190

### CODE REVIEW

**Comment by CartBlanche** [comment]
@adrianstevens I think it is only a couple of lines change, but the diff shows a lot more. Is that a white space issue?

**Comment by adrianstevens** [comment]
@CartBlanche yeah I suspect I hit yes when VS asked about normalizing line endings (habit).

I can undo it if you prefer.

**Comment by CartBlanche** [comment]
@adrianstevens If it's possible, yet please. Just so it's clearer what what the actual changes are. Let me know if it doesn't work, and I'll try to fix it here and will send a commit.

**Comment by CartBlanche** [comment]
Closed as ported changes to have a cleaner PR.

**Pull request closed without merging**
