### PR TITLE
adding progress bar support through logger

### PR DESCRIPTION
**Pull request by ctacke**

### CODE REVIEW

**Comment by CartBlanche** [comment]
@ctacke I tested this on both Mac and Windows, in their respective VSs, and it shows sporadic progress. I've not done a manual deploy yet, to see it in full effect.

**Comment by CartBlanche** [comment]
I just tested CLI `meadow app deploy` and noticed this every once in a while...
```
Writing file: NetEscapades.Configuration.Yaml.dll
Starting File Transfer...
[===============================================   ] NetEscapades.Configuration.Yaml.dlMeadow StdInfo: File 72% downloaded
Meadow StdInfo: File 81% downloaded
Meadow StdInfo: File 90% downloaded
Meadow StdInfo: Download of 'NetEscapades.Configuration.Yaml.dll' success (checksums calculated:0x17208F9E, expected:0x17208F9E)
```

So it's using the progress bar for most of it, then dropping to old school `File 81% downloaded` towards the end.

**Comment by ctacke** [comment]
@CartBlanche the progress will only appear for file writes, not for things like os/esp firmware uploads.  Are you saying that only some files show progress, or only partial progress on files?

**Comment by CartBlanche** [comment]
@ctacke The above example is a file write. Notice it starts with 
`Writing file: NetEscapades.Configuration.Yaml.dll`
then ends with 
`Meadow StdInfo: Download of 'NetEscapades.Configuration.Yaml.dll' success (checksums calculated:0x17208F9E, expected:0x17208F9E)`

And it happens for more than one file on the command line.

**Pull request closed without merging**
